[default]
action = "copy"
output_path = "~/Desktop/Projects/your-project/dist/combined.txt"

[ignore]
patterns = [
  ".DS_Store",
  ".ipynb_checkpoints/",
  "node_modules",
  "**pycache**",
  "untracked/",
  "dist/",
  "target/",
  ".env",
  ".ipynb",
  ".lock",
  "constants.py",
  "constants.rs",
]
