[default]
action = "copy"
use_relative_paths = true
ignore_patterns = [
  ".DS_Store",
  ".env",
  ".ipynb",
  ".lock",
  ".ipynb_checkpoints/",
  "node_modules/",
  "**pycache**",
  "dist/",
  "target/",
  "constants.py",
]
