[package]
name = "project-code-combinator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard = "0.5.0"
ignore = "0.4.22"
regex = "1.5.4"
