name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Extract version from tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update version in Cargo.toml
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          sed -i 's/version = ".*"/version = "$VERSION"/' Cargo.toml

      - name: Commit and push changes
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          git config --local user.email "claudioropez.k@gmail.com"
          git config --local user.name "Kazunori Osaki"
          git add Cargo.toml
          git commit -m "Update version to $VERSION"
          git push origin main

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
