name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Extract version from tag
        run: |
          if [[ $GITHUB_REF =~ ^refs/tags/v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            echo "VERSION=${BASH_REMATCH[1]}" >> $GITHUB_ENV
          else
            echo "Invalid tag format. Skipping release."
            exit 1
          fi

      - name: Update version in Cargo.toml
        run: |
          sed -i 's/^version = ".*"/version = "$VERSION"/' Cargo.toml

      - name: Commit and push changes
        run: |
          git config --local user.email "claudioropez.k@gmail.com"
          git config --local user.name "Kazunori Osaki"
          git add Cargo.toml
          git commit -m "Update version to $VERSION"
          git push origin main

      - name: Build release package
        run: |
          cargo build --release

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          files: target/release/pcc
